### ISSUE TITLE
No module named 'semantic_parsing_with_constrained_lm.finetune.platypus'

### ISSUE THREAD

**Issue by hankcs** [microsoft/semantic_parsing_with_constrained_lm#13]
Dear authors, your package is not complete. `platypus` is missing but referred here.

https://github.com/microsoft/semantic_parsing_with_constrained_lm/blob/7041371a8f1371c3da7f115ef366a0ff9001dbbd/src/semantic_parsing_with_constrained_lm/domains/lispress_v2/create_benchclamp_data.py#L33

**Comment by rshin** [comment]
Thanks for your report. It should now be resolved.
